# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 02:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Functionary',
        ),
        migrations.DeleteModel(
            name='Matriculation',
        ),
        migrations.DeleteModel(
            name='School',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
    ]
