# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-07 10:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CommonInfo',
            fields=[
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('cpf', models.CharField(max_length=11, primary_key=True, serialize=False, verbose_name='CPF')),
                ('date_of_birth', models.DateField(verbose_name='data de nascimento')),
                ('race', models.CharField(max_length=100, verbose_name='raça')),
                ('rg', models.CharField(max_length=100, verbose_name='RG')),
                ('dispatch_entity_rg', models.CharField(max_length=100, verbose_name='orgão expedidor do RG')),
                ('gender', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=20, verbose_name='sexo')),
                ('nationality', models.CharField(max_length=100, verbose_name='nacionalidade')),
                ('naturalness', models.CharField(max_length=100, verbose_name='naturalidade')),
            ],
        ),
        migrations.CreateModel(
            name='Matriculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('company_name', models.CharField(max_length=100, verbose_name='nome da escola')),
                ('cnpj', models.CharField(max_length=14, primary_key=True, serialize=False, verbose_name='CNPJ')),
                ('number_inep', models.CharField(max_length=100, verbose_name='inscrição do INEP')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'verbose_name_plural': 'escolas',
                'verbose_name': 'escola',
                'ordering': ('-created_at',),
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='management.CommonInfo')),
                ('matriculation', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='matrícula')),
                ('status', models.CharField(choices=[('A', 'Ativo'), ('D', 'Desativado'), ('E', 'Em Curso'), ('C', 'Concluindo')], max_length=10, verbose_name='situação')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('cell_phone', models.CharField(max_length=20, verbose_name='celular')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.School', verbose_name='escola')),
            ],
            options={
                'verbose_name_plural': 'alunos',
                'verbose_name': 'aluno',
                'ordering': ('-created_at',),
            },
            bases=('management.commoninfo',),
        ),
    ]
