# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-06 02:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Functionary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('date_of_birth', models.DateField()),
                ('race', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=100)),
                ('dispatch_entity_rg', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('naturalness', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Matriculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=14)),
                ('number_inep', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('cpf', models.CharField(max_length=11, verbose_name='CPF')),
                ('date_of_birth', models.DateField()),
                ('race', models.CharField(max_length=100)),
                ('rg', models.CharField(max_length=100)),
                ('dispatch_entity_rg', models.CharField(max_length=100)),
                ('gender', models.CharField(max_length=100)),
                ('nationality', models.CharField(max_length=100)),
                ('naturalness', models.CharField(max_length=100)),
                ('matriculation', models.CharField(max_length=100)),
                ('status', models.BooleanField()),
                ('school', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('cell_phone', models.CharField(max_length=20, verbose_name='celular')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('functionary_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='management.Functionary')),
            ],
            options={
                'abstract': False,
            },
            bases=('management.functionary',),
        ),
    ]
