# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-16 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import educarinova.management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculation',
            name='number_matriculation',
            field=models.IntegerField(default=educarinova.management.models.random_string, verbose_name='matrícula'),
        ),
        migrations.AlterField(
            model_name='matriculation',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Student', verbose_name='aluno'),
        ),
        migrations.AlterField(
            model_name='matriculation',
            name='tuition_fee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.TuitionFee', verbose_name='mensalidade'),
        ),
        migrations.AlterField(
            model_name='tuitionfee',
            name='discount_tuition_fee',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='desconto na mensalidade'),
        ),
        migrations.AlterField(
            model_name='tuitionfee',
            name='expiration_day',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27')], max_length=2, verbose_name='dia de vencimento'),
        ),
        migrations.AlterField(
            model_name='tuitionfee',
            name='frequency_payment',
            field=models.CharField(choices=[('Mensal', 'Mensal'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], max_length=30, verbose_name='frequência de pagamento'),
        ),
        migrations.AlterField(
            model_name='tuitionfee',
            name='reason_discount_tuition_fee',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='motivo do desconto'),
        ),
    ]
