# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-06 17:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AddField(
            model_name='class',
            name='matriculation',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='management.Matriculation', verbose_name='matricula'),
        ),
        migrations.AddField(
            model_name='class',
            name='vagas',
            field=models.CharField(default="0", max_length=10, verbose_name='vagas'),
        ),
        migrations.AddField(
            model_name='matriculation',
            name='created_at',
            field=models.DateTimeField(null=True, verbose_name='criado em'),
        ),
        migrations.AddField(
            model_name='matriculation',
            name='number_matriculation',
            field=models.IntegerField(blank=True, null=True, verbose_name='matricula'),
        ),
        migrations.AddField(
            model_name='matriculation',
            name='status',
            field=models.CharField(max_length=14, null=True, verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matriculation',
            field=models.OneToOneField(default=False, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management.Matriculation', verbose_name='matrícula'),
        ),
        migrations.AddField(
            model_name='matriculation',
            name='attendance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.Attendance', verbose_name='frequência'),
        ),
        migrations.AddField(
            model_name='matriculation',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Score', verbose_name='nota'),
        ),
    ]
