# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-09 18:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='dispatch_entity_rg',
            field=models.CharField(choices=[('SSP', 'SSP'), ('IML', 'IML'), ('ITEP', 'ITEP'), ('ITCP', 'ITCP')], max_length=4, verbose_name='orgão expedidor do RG'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='gender',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino')], max_length=1, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='nationality',
            field=models.CharField(choices=[('AR', 'Argentino(a)'), ('BR', 'Brasileiro(a)'), ('CA', 'Canadiano(a)'), ('CL', 'Chileno(a)'), ('CO', 'Colombiano(a)'), ('CU', 'Cubano(a)'), ('US', 'Norte-americano(a)'), ('MX', 'Mexicano(a)'), ('VE', 'Venezuelano(a)')], max_length=2, verbose_name='nacionalidade'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='race',
            field=models.CharField(choices=[('BC', 'BRANCO(A)'), ('PD', 'PARDO(A)'), ('PT', 'PRETO(A)'), ('AL', 'AMARELO(A)'), ('IN', 'INDÍGENA(A)')], max_length=2, verbose_name='raça'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('A', 'Ativo'), ('D', 'Desativado'), ('E', 'Em Curso'), ('C', 'Concluindo')], max_length=1, verbose_name='situação'),
        ),
    ]
