# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 15:14
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import educarinova.management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20160412_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identification', models.CharField(max_length=100, verbose_name='Identificação da sala')),
                ('type', models.CharField(choices=[('Sala de Aula', 'Sala de Aula'), ('Laboratório', 'Laboratório'), ('Outro', 'Outro')], max_length=30, verbose_name='tipo de sala')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cell_phone', models.CharField(max_length=20, verbose_name='celular')),
                ('cell_phone_secondary', models.CharField(blank=True, max_length=20, null=True, verbose_name='outro celular')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone¹')),
                ('phone_secondary', models.CharField(blank=True, max_length=20, null=True, verbose_name='telefone²')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('fax', models.CharField(blank=True, max_length=20, null=True, verbose_name='fax')),
            ],
        ),
        migrations.CreateModel(
            name='Matriculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number_matriculation', models.IntegerField(default=educarinova.management.models.random_string, verbose_name='matricula')),
                ('status', models.CharField(choices=[('Ativo', 'Ativo'), ('Desativado', 'Desativado'), ('Em Curso', 'Em Curso'), ('Concluido', 'Concluido')], max_length=10, null=True, verbose_name='situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20, verbose_name='série')),
                ('level', models.CharField(choices=[('Creche', 'Creche'), ('Infantil', 'Infantil'), ('Fundamental', 'Fundamental'), ('Médio', 'Médio'), ('Outro', 'Outro')], max_length=25, verbose_name='nível')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='nome da disciplina')),
            ],
        ),
        migrations.AddField(
            model_name='matriculation',
            name='attendance',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='management.Attendance', verbose_name='frequência'),
        ),
        migrations.AddField(
            model_name='matriculation',
            name='score',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Score', verbose_name='nota'),
        ),
        migrations.AddField(
            model_name='classroom',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Unit', verbose_name='unidade escolar'),
        ),
        migrations.AddField(
            model_name='class',
            name='matriculation',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='management.Matriculation', verbose_name='matricula'),
        ),
        migrations.AddField(
            model_name='class',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Serie', verbose_name='série'),
        ),
        migrations.AddField(
            model_name='class',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Unit', verbose_name='unidade escolar'),
        ),
    ]
