# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-17 16:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20160416_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='shift',
            field=models.CharField(choices=[('M', 'Matutino'), ('V', 'Vespertino'), ('N', 'Noturno'), ('O', 'Outro')], max_length=10, verbose_name='turno'),
        ),
    ]
