# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 11:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import educarinova.management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20160406_1427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='status',
        ),
        migrations.AddField(
            model_name='class',
            name='serie',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Serie', verbose_name='serie'),
        ),
        migrations.AddField(
            model_name='class',
            name='unit',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Unit', verbose_name='unidade escolar'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type_of_street',
            field=models.CharField(choices=[('Rua', 'Rua'), ('Avenida', 'Avenida')], max_length=100, verbose_name='tipo de logradouro'),
        ),
        migrations.AlterField(
            model_name='matriculation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='criado em'),
        ),
        migrations.AlterField(
            model_name='matriculation',
            name='number_matriculation',
            field=models.IntegerField(default=educarinova.management.models.random_string, verbose_name='matricula'),
        ),
        migrations.AlterField(
            model_name='matriculation',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Desativado', 'Desativado'), ('Em Curso', 'Em Curso'), ('Concluido', 'Concluido')], max_length=10, null=True, verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matriculation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management.Matriculation', verbose_name='matrícula'),
        ),
    ]
