# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20160412_1545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculation',
            name='attendance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Attendance', verbose_name='frequência'),
        ),
        migrations.AlterField(
            model_name='matriculation',
            name='score',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Score', verbose_name='nota'),
        ),
        migrations.AlterField(
            model_name='student',
            name='matriculation',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='management.matriculation', verbose_name='matrícula'),
        ),
    ]
