# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-14 15:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20160414_1459'),
    ]

    operations = [
        migrations.RenameField(
            model_name='address',
            old_name='CEP',
            new_name='cep',
        ),
        migrations.RenameField(
            model_name='commoninfo',
            old_name='CPF',
            new_name='cpf',
        ),
    ]
