# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-22 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_auto_20160417_1614'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tuitionfee',
            name='discount_tuition_fee',
            field=models.DecimalField(blank=True, decimal_places=0, default=0, max_digits=3, null=True, verbose_name='desconto na mensalidade'),
        ),
    ]
