# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 16:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20160412_1637'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='matricula',
            new_name='matriculation',
        ),
    ]
