# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-25 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0005_auto_20160424_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matriculation',
            name='status',
            field=models.CharField(choices=[('success', 'Ativo'), ('danger', 'Desativado'), ('warning', 'Em Análise'), ('info', 'Em Curso'), ('closed', 'Concluido')], default='Em Curso', max_length=10, null=True, verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='tuitionfee',
            name='expiration_day',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20'), ('21', '21'), ('22', '22'), ('23', '23'), ('24', '24'), ('25', '25'), ('26', '26'), ('27', '27')], default=5, max_length=2, verbose_name='dia de vencimento'),
        ),
        migrations.AlterField(
            model_name='tuitionfee',
            name='frequency_payment',
            field=models.CharField(choices=[('Mensal', 'Mensal'), ('Bimestral', 'Bimestral'), ('Trimestral', 'Trimestral'), ('Semestral', 'Semestral'), ('Anual', 'Anual')], default='Mensal', max_length=30, verbose_name='frequência de pagamento'),
        ),
    ]
