# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 02:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_student_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=20, verbose_name='telefone')),
                ('phone_secondary', models.CharField(max_length=20, verbose_name='outro telefone')),
                ('cell_phone', models.CharField(max_length=20, verbose_name='celular')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('fax', models.CharField(max_length=20, verbose_name='fax')),
            ],
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome da escola')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('contact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Contact', verbose_name='contato')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.School', verbose_name='escola')),
            ],
        ),
        migrations.RemoveField(
            model_name='student',
            name='cell_phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='email',
        ),
        migrations.RemoveField(
            model_name='student',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='student',
            name='school',
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='race',
            field=models.CharField(choices=[('Branco(a)', 'Branco(a)'), ('Pardo(a)', 'Pardo(a)'), ('Preto(a)', 'Preto(a)'), ('Amarelo(a)', 'Amarelo(a)'), ('Indígeno(a)', 'Indígeno(a)')], max_length=2, verbose_name='raça'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Desativado', 'Desativado'), ('Em Curso', 'Em Curso'), ('Concluido', 'Concluido')], max_length=1, verbose_name='situação'),
        ),
        migrations.AlterField(
            model_name='student',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='student',
            name='contact',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='management.Contact', verbose_name='contato'),
        ),
        migrations.AddField(
            model_name='student',
            name='unit',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='management.Unit', verbose_name='unidade'),
        ),
    ]
