# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-05-24 18:28
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0007_auto_20160509_1514'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_by_user', to=settings.AUTH_USER_MODEL, verbose_name='criado por'),
        ),
        migrations.AddField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('info', 'Ativo'), ('danger', 'Desativado')], default='Ativo', max_length=10, null=True, verbose_name='situação'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_at',
            field=models.DateTimeField(null=True, verbose_name='atualizado em'),
        ),
        migrations.AddField(
            model_name='student',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='updated_by_user', to=settings.AUTH_USER_MODEL, verbose_name='atualizado por'),
        ),
        migrations.AlterField(
            model_name='responsiblestudent',
            name='kinship',
            field=models.CharField(choices=[('Pai/Mãe', 'Pai/Mãe'), ('Irmão/Irmã', 'Irmão/Irmã'), ('Tio(a)', 'Tio(a)'), ('Avô(ó)', 'Avô(ó)'), ('Outro parentesco', 'Outro parentesco')], max_length=20, verbose_name='parentesco'),
        ),
    ]
