# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-12 17:09
from __future__ import unicode_literals

from django.db import migrations, models
import educarinova.management.models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_auto_20160412_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='matriculation',
            name='number_matriculation',
            field=models.IntegerField(default=educarinova.management.models.random_string, primary_key=True, serialize=False, verbose_name='matricula'),
        ),
    ]
