# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 03:02
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('management', '0008_auto_20160312_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('commoninfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, to='management.CommonInfo')),
                ('matriculation', models.CharField(max_length=100, primary_key=True, serialize=False, verbose_name='matrícula')),
                ('function', models.CharField(choices=[('Diretor(a)', 'Diretor(a)'), ('Vice-Diretor(a)', 'Vice-Diretor(a)'), ('Secretário(a)', 'Secretário(a)'), ('Coordenador(a)', 'Coordenador(a)'), ('Pedagogo(a)', 'Pedagogo(a)'), ('Professor(a)', 'Professor(a)'), ('Porteiro(a)', 'Porteiro(a)'), ('Outro', 'Outro')], max_length=25, verbose_name='função')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
            ],
            bases=('management.commoninfo',),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cell_phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='phone_secondary',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='outro telefone'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nome da unidade'),
        ),
        migrations.AddField(
            model_name='employee',
            name='contact',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='management.Contact', verbose_name='contato'),
        ),
        migrations.AddField(
            model_name='employee',
            name='unit',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='management.Unit', verbose_name='unidade'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
