# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-08-17 18:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20160817_1428'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='period',
        ),
    ]
