# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-13 03:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0009_auto_20160313_0002'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='CEP',
            field=models.CharField(default=False, max_length=9, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default=False, max_length=100, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='address',
            name='complement',
            field=models.CharField(default=False, max_length=100, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='address',
            name='district',
            field=models.CharField(default=False, max_length=100, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='address',
            name='house_number',
            field=models.CharField(default=False, max_length=6, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='address',
            name='state',
            field=models.CharField(default=False, max_length=100, verbose_name='estado'),
        ),
        migrations.AddField(
            model_name='address',
            name='street',
            field=models.CharField(default=False, max_length=100, verbose_name='logradouro'),
        ),
        migrations.AddField(
            model_name='address',
            name='type_of_street',
            field=models.CharField(default=False, max_length=100, verbose_name='tipo de logradouro'),
        ),
        migrations.AddField(
            model_name='employee',
            name='address',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='management.Address', verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='student',
            name='address',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='management.Address', verbose_name='endereço'),
        ),
        migrations.AddField(
            model_name='unit',
            name='address',
            field=models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='management.Address', verbose_name='endereço'),
        ),
    ]
