# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 16:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_auto_20160322_0940'),
    ]

    operations = [
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome da sala')),
                ('type', models.CharField(choices=[('Sala de Aula', 'Sala de Aula'), ('Laboratório', 'Laboratório'), ('Outro', 'Outro')], max_length=30, verbose_name='tipo de sala')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Unit', verbose_name='unidade')),
            ],
        ),
        migrations.AlterField(
            model_name='address',
            name='CEP',
            field=models.CharField(max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(max_length=100, verbose_name='cidade'),
        ),
        migrations.AlterField(
            model_name='address',
            name='complement',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='complemento'),
        ),
        migrations.AlterField(
            model_name='address',
            name='district',
            field=models.CharField(max_length=100, verbose_name='bairro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=6, verbose_name='número'),
        ),
        migrations.AlterField(
            model_name='address',
            name='state',
            field=models.CharField(max_length=100, verbose_name='estado'),
        ),
        migrations.AlterField(
            model_name='address',
            name='street',
            field=models.CharField(max_length=100, verbose_name='logradouro'),
        ),
        migrations.AlterField(
            model_name='address',
            name='type_of_street',
            field=models.CharField(max_length=100, verbose_name='tipo de logradouro'),
        ),
        migrations.AlterField(
            model_name='commoninfo',
            name='race',
            field=models.CharField(choices=[('Branco(a)', 'Branco(a)'), ('Pardo(a)', 'Pardo(a)'), ('Preto(a)', 'Preto(a)'), ('Amarelo(a)', 'Amarelo(a)'), ('Indígeno(a)', 'Indígeno(a)')], max_length=12, verbose_name='raça'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='cell_phone',
            field=models.CharField(max_length=20, verbose_name='celular'),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Desativado', 'Desativado'), ('Em Curso', 'Em Curso'), ('Concluido', 'Concluido')], max_length=10, verbose_name='situação'),
        ),
    ]
