# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_auto_20160329_1305'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classroom',
            name='name',
        ),
        migrations.AddField(
            model_name='classroom',
            name='identification',
            field=models.CharField(default=datetime.datetime(2016, 3, 29, 18, 54, 15, 698680, tzinfo=utc), max_length=100, verbose_name='Identificação da sala'),
            preserve_default=False,
        ),
    ]
