# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-29 21:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_auto_20160329_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Serie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(max_length=20, verbose_name='série')),
                ('level', models.CharField(choices=[('Creche', 'Creche'), ('Infantil', 'Infantil'), ('Fundamental', 'Fundamental'), ('Médio', 'Médio'), ('Outro', 'Outro')], max_length=25, verbose_name='nível')),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.Unit', verbose_name='unidade escolar'),
        ),
    ]
